runtime: aspnetcore
env: flex

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  ASPNETCORE_ENVIRONMENT: Production
  Jwt__Secret: super-secret-key-at-least-256-bits-to-be-strong
  Jwt__Issuer: FavGame
  Jwt__Audience: FavGame-client
  Rawg__ApiKey: <secret-key>
  Youtube__ApiKey: <secret-key>
  ConnectionStrings__DefaultConnection: Host=/cloudsql/gcloud-w3:europe-west1:db-app;Username=postgres;Password=<password>;Database=db-game

beta_settings:
  cloud_sql_instances: gcloud-w3:europe-west1:db-favgame
